I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 74, in script
    show Ex with dissolve(3.0)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 74, in script
    show Ex with dissolve(3.0)
  File "C:\Users\Lenovo\Downloads\Programs\renpy-8.2.3-sdk\renpy\ast.py", line 1363, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "C:\Users\Lenovo\Downloads\Programs\renpy-8.2.3-sdk\renpy\exports.py", line 1782, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\Lenovo\Downloads\Programs\renpy-8.2.3-sdk\renpy\display\core.py", line 1549, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\Lenovo\Downloads\Programs\renpy-8.2.3-sdk\renpy\display\core.py", line 2166, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\Lenovo\Downloads\Programs\renpy-8.2.3-sdk\renpy\display\core.py", line 2609, in interact_core
    trans = instantiate_transition(None, old_root, layers_root)
  File "C:\Users\Lenovo\Downloads\Programs\renpy-8.2.3-sdk\renpy\display\core.py", line 2519, in instantiate_transition
    trans = self.ongoing_transition[layer](
TypeError: 'Dissolve' object is not callable

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
suki life 1.0
Tue Jul 16 11:08:32 2024
